### ISSUE TITLE
mackerel_service create failure if memo includes "&"

### ISSUE THREAD

**Issue by sogaoh** [mackerelio-labs/terraform-provider-mackerel#58] opened 2021-08-09 10:02 UTC
## Setting to reproduce

```
resource "mackerel_service" "foo" {
  name = "foo"
  memo = "foo&"
}
```

### actual

```
Error: API request failed: Internal server error.
```

### expected

```
mackerel_service.foo: Creation complete
```

## Note

- Probably occurs on `mackerel_role`, too.
- My workaround is using full width `＆` not half width `&` 

### Environment 
(2021/8/11 Add)
- terraform 1.0.4
- terraform-provider-mackerel 0.0.3

**Comment by sogaoh** [comment] 2021-08-11 14:01
Slack でもお伝えしたのですが、改めて再現確認を行ったところ全く起きなかったので対応の優先度は下げていただいて良いです。。

**Comment by hayajo** [comment] 2021-08-12 01:05
Thank you for double-checking.

I think the error is due to a temporary problem with the service.
Please change the value of memo to `foo&` and try again.

**Comment by hayajo** [comment] 2021-08-12 03:25
Since this is caused by a temporary service error, please let me close this Issue.
If the problem occurs again, please reopen the Issue.

**Closed by hayajo** 2021-08-12 03:25 UTC
